### ISSUE TITLE
TrackInfo appears when it shouldn't

### ISSUE THREAD

**Issue by Syncrossus** [Squadella/ManaZeak#21]
Context : cursor is dragged swiftly across the screen without pausing to hover over a song and stops shortly after having passed over a song
Expected behavior : Nothing happens
Actual behavior : An infobox flashes momentarily after the cursor has stopped

**Comment by Oxydiz** [comment]
Fixed as of 8bf50481f7451b6f014c66d849a5dd7b5b15cc18

**Comment by Syncrossus** [comment]
This issue is still occuring as of [`aae1d99`](https://github.com/Squadella/ManaZeak/commit/aae1d99c62b47db0be93220ef0c94135bdb18b4e)

**Comment by Syncrossus** [comment]
This issue is still occurring in production version
